### ISSUE TITLE
ILIAS 5.0.x und Responsive Design

### ISSUE THREAD

**Issue by mhilbert** [studer-raimann/SystemNotifications#10]
Unter ILIAS 5.0.x zerschießt die Notification bei kleiner Bildschirmauflösung ein wenig das Responsive Design (siehe angehängte Screenshots einmal mit und einmal ohne Notification). Das X zum Entfernen der Notification lässt sich durch das Überlappen mit der Überschrift nicht bedienen.
(getestet mit SystemNotifications 1.2.1 unter ILIAS 5.0.4)

![responsive design mit systemnotification](https://cloud.githubusercontent.com/assets/13761573/9218913/f2de7542-40d6-11e5-9949-c7405b571d02.png)
![responsive design ohne systemnotification](https://cloud.githubusercontent.com/assets/13761573/9218915/f8cbb14a-40d6-11e5-8ea9-8d053f62bf1e.png)

**Comment by mhilbert** [comment]
Ich habe gerade gesehen, dass Ihr anders als in der Plug-In-Datensammlung angegeben, Mantis als Bug-Tracker nutzt, daher habe ich diesen Issue nun besser dort eingestellt:
http://ilias.de/mantis/view.php?id=16363
Dann könnt Ihr ihn hier vielleicht löschen?

**Comment by chfsx** [comment]
Du kannst gerne Bugs auch hier melden, wir prüfen beide Datenbanken. Ich schliesse aber diese hier mal, da du bereits in Mantis auch eröffnet hast. Vielen Dank für deine Inputs!
