### ISSUE TITLE
Sekundengenaue Zeitangabe eines Events

### ISSUE THREAD

**Issue by mhilbert** [studer-raimann/SystemNotifications#11]
Eine Notification sowie ein zugehöriges Event lassen sich minutengenau einstellen, was auch völlig ausreichend ist.
Die Zeitangabe des Events in der Notification zeigt zusätzlich allerdings auch Sekunden an, was in meinen Augen überflüssig ist, z.B.
"13.08.2015 10:00:00 - 13.08.2015 20:00:00".

Wenn Anfangs- und Enddatum des Events gleich sind, könnte man die Ausgabe hier sogar zusätzlich vereinfachen (und für den Benutzer übersichtlicher machen):
"13.08.2015, 10:00 - 20:00 Uhr"

**Comment by chfsx** [comment]
Du kannst gerne Bugs auch hier melden, wir prüfen beide Datenbanken. Ich schliesse aber diese hier mal, da du bereits in Mantis auch eröffnet hast. Vielen Dank für deine Inputs!

http://ilias.de/mantis/view.php?id=16364

**Comment by mhilbert** [comment]
Okay, danke!
